[package]
name = "first_rust_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashmap = "0.0.1"
postgres = "0.19.5"
toolchain = "0.1.0-alpha.1"
